---
- name: Create user accounts
  hosts: "{{ HOSTS | default('web') }}"
  become: true
  vars:
    users:
      - dalee
      - tester
      - deleteme
  
  tasks:
    - name: Create user accounts
      user:
        name: "{{ item }}"
        state: present
        groups: "wheel"
      loop: users
        
