---
- name: Remove user accounts
  hosts: "{{ HOSTS | default('web') }}"
  become: true
  vars:
    users:
      - tester
      - deleteme
  
  tasks:
    - name: Remove user accounts
      user:
        name: "{{ item }}"
        state: absent
        remove: yes
      loop: "{{ users }}"
        
